#!/bin/bash

read -p "enter user name:" USERNAME

SPECIAL="@#$%^&*"
PASS=`echo $SPECIAL | fold -w1 | shuf | head -1`
PASSWORD=INDIA$PASS$RANDOM

EXUSER=`cat /etc/passwd | grep -i $USERNAME | cut -d ":" -f1`

if [[ $EXUSER == $USERNAME ]]
then
echo "user alredy exist"
else
useradd -m $USERNAME
echo $PASSWORD | passwd --stdin $USERNAME
passwd -e $USERNAME
echo $USERNAME $PASSWORD
fi

